run:
  # generate | evaluate | report | all
  mode: generate

dhmf:
  config_path: example/a/config_open.yaml
  query_mode: agent  # dual_path | agent

paths:
  db_path: example/a/DB/main.db
  output_dir: benchmark_results

  # generate 写出
  questions_filename: questions_all-easy_100.json
  questions_path: null

  # evaluate 读入
  eval_questions_filename: questions_standard_100_agent.json
  eval_questions_path: null
  # evaluate 写出
  eval_results_filename: eval_report_standard_100_agent.json
  eval_results_path: null

  # report 读入
  report_source_filename: null
  report_source_path: null
  # report 写出
  report_filename: report_standard_100_agent.json
  report_path: null

generate:
  hop_counts:
    "1": 100
    "2": 0
    "3": 0
  seed: 42
  max_chars_per_doc: -1
  max_retries: 3
  sleep_between: 0.0
  num_thread: 4          #
  use_cache: false
  api_key: null
  base_url: null
  timeout: 180
  model_args:
    model: null
    temperature: 0.2
    enable_thinking: false
    response_format:
      type: json_object

evaluate:
  enable_doc_recall: False
  max_source_chars: -1
  max_retries: 3
  sleep_between: 0.0
  use_cache: false
  dhmf_retrieve_use_cache: null
  api_key: null
  base_url: null
  timeout: 180
  model_args:
    model: null
    temperature: 0.0
    enable_thinking: false
    response_format:
      type: json_object

report:
  print_table: true  # 终端打印文本统计表

logging:
  level: INFO
